### PR TITLE
Fix Dictionary ordering in TestHTTPURLResponse.test_NSCoding 

### PR DESCRIPTION
**Pull request by jrflat**
`TestHTTPURLResponse.test_NSCoding` was sometimes failing after #5019 since Dictionary ordering can be unpredictable when encoding/decoding, e.g.

```
TestFoundation/TestHTTPURLResponse.swift:239: error: TestHTTPURLResponse.test_NSCoding : XCTAssertEqual failed: ("[AnyHashable("Content-Disposition"), AnyHashable("Content-Type")]") is not equal to ("[AnyHashable("Content-Type"), AnyHashable("Content-Disposition")]") - Archived then unarchived http url response must be equal.
```

This PR makes a small change to the test to compare Sets of the keys instead.

### CODE REVIEW

**Comment by jrflat** [comment]
@swift-ci please test

**Comment by jrflat** [comment]
@swift-ci please test Linux

**Comment by rintaro** [comment]
https://github.com/swiftlang/swift/pull/77414
@swift-ci Please test

**Review by Coeur — APPROVED** [review]
