### ISSUE TITLE
`Data(contentsOf:)` regression on Windows in Swift 5.10

### ISSUE THREAD

**Issue by tishin** [swiftlang/swift-corelibs-foundation#4921]
A simple script to reproduce the issue:
```swift
import Foundation

let url = URL(fileURLWithPath: "/Projects/file.txt")
if FileManager.default.fileExists(atPath: url.path) {
    print(try Data(contentsOf: url))
}
```
It works in Swift 5.9.2 release, but throws an error in Swift 5.10 release:
```
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"
Current stack trace:
0    (null)                             0x00007ffca6a24ae0 swift_stdlib_reportFatalErrorInFile + 132
```

Swift version 5.10 (swift-5.10-RELEASE)
Target: x86_64-unknown-windows-msvc
OS Version: 10.0.19045 N/A Build 19045

Possibly introduced by #4802

**Comment by stefanspringer1** [comment]
With Swift 6.1.1 the program

```swift
import Foundation

let url = URL(string: "https://raw.githubusercontent.com/jmespath/jmespath.test/master/tests/filters.json")!
do {
    _ = try Data(contentsOf: url)
} catch {
    print(error.localizedDescription)
}
```

prints `The specified URL type isn’t supported.` but the program

```swift
import Foundation

let url = URL(string: "https://raw.githubusercontent.com/jmespath/jmespath.test/master/tests/filters.json")!
_ = try Data(contentsOf: url)
```

does not print such an "understandable" error message. But it does so on Linux.

It would be nice if such crashes on Windows would also print the localizedDescription.

**Comment by parkera** [comment]
Does this still reproduce on 6.1 or later?

**Comment by parkera** [comment]
I agree with tracking #4582 separately.
